name: Docs Test and Publish

on: push

jobs:
  helm-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: myOtherJob1
    #   run:

    - name: Test Docs generation
      uses: draios/infra-ghaction-mark2confluence@main
      with:
        action: "test"
      env:
        BASE_URL: https://core-io.atlassian.net
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}

    - name: Publish Docs
      uses: draios/infra-ghaction-mark2confluence@main
      with:
        action: "publish"
      env:
        BASE_URL: https://core-io.atlassian.net
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
