name: Docs Test and Publish

on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: myOtherJob1
    #   run:

    - name: Test Docs generation
      uses: drscream/infra-action-mark2confluence@main
      with:
        action: "dry-test"
        CONFLUENCE_BASE_URL: https://core-io.atlassian.net/wiki
        DOC_DIR_PATTERN: ".*"
        DOC_DIR: docs
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}

    - name: Publish Docs
      uses: drscream/infra-action-mark2confluence@main
      with:
        action: "publish"
        CONFLUENCE_BASE_URL: https://core-io.atlassian.net/wiki
        DOC_DIR_PATTERN: ".*"
        DOC_DIR: docs
        CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
